version: '3.3'
services:
  minio:
    image: minio/minio:RELEASE.2022-06-30T20-58-09Z.fips
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    volumes:
      - ./_docker/minio:/data
    ports:
      - "9000:9000"
    command: server /data --console-address :46666
    restart: unless-stopped
    container_name: minio-sandbox